### PR TITLE
Adds OpenLDAP-based Search-and-Destroy Capability

### PR DESCRIPTION
**Pull request by ferricoxide**
New functionality delivered as a multi-mode, flag/option script. Allows use both via associated Saltstack state and as an interactive script.

If used via saltstack:
* Will output Salt-compatible logging
* Will (always) attempt a search-and-destroy using same Pillar data used for PBIS.
~~~
local:
----------
          ID: RPM-installs
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 23:01:49.891216
    Duration: 1072.355 ms
     Changes:
----------
          ID: LDAP-FindCollison
    Function: cmd.script
        Name: find-collisions.sh -d "<DNS.STYLE.DOMAIN.NAME>" -u "<DIRECTORY_USER>" -c "<CRYPT_STRING>" -k "<DECRYPT_KEY>" --mode saltstack
      Result: True
     Comment: Delete of computer-object succeeded
     Started: 23:01:50.965369
    Duration: 231.261 ms
     Changes:
              ----------
              changed:
                  yes
              pid:
                  15281
              retcode:
                  0
              stderr:
              stdout:

Summary for local
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
Total run time:   1.304 s
~~~

If used interactively:
* Arguments will need to be manually specified
* Nuke-action is optional
* Output format is optional
* Operates in a debug mode by setting `DEBUG` environmental (otherwise success is silent)
~~~
$ DEBUG=true bash +x join-domain-formula/join-domain/elx/openldap-client/files/find-collisions.sh -d ad.test.internal -u <LDAP_USER> -c '<CRYPT_STRING>' -k '<CRYPT_KEY>'
Contact aws-c2c4418931.ad.test.internal. on port 389
Found CN=ISSUE106,CN=Computers,DC=ad,DC=test,DC=internal

$ DEBUG=true bash +x join-domain-formula/join-domain/elx/openldap-client/files/find-collisions.sh -d ad.test.internal -u <LDAP_USER> -c '<CRYPT_STRING>' -k '<CRYPT_KEY>' --mode cleanup
Contact aws-c2c4418931.ad.test.internal. on port 389
Found CN=ISSUE106,CN=Computers,DC=ad,DC=test,DC=internal
Delete of CN=ISSUE106,CN=Computers,DC=ad,DC=test,DC=internal succeeded
~~~

### CODE REVIEW

**Comment by ferricoxide** [comment]
Goddammit. I thought the openldap-clients' `init.sls` would only be called if one of the higher-level init.sls`es referenced it. ಠ_ಠ

**Comment by lorengordon** [comment]
The call is made here, https://github.com/plus3it/join-domain-formula/blob/master/join-domain/elx/init.sls. Would need to update the project directories and update that file accordingly to change how that works. If `openldap-clients` isn't intended to be a connector, could probably create a `connectors` directory, and modify the reference to `.connectors.{{ad_connector}}`.

**Comment by ferricoxide** [comment]
It's _eventually_ meant to be a connector (the original-original plan was to make states for each of the main connector-options for integrating ELx with AD domains). The current tools is being done, now, due to the issues with `adtool` (i.e., [Issue](https://github.com/BeyondTrust/pbis-open/issues/203)).

So, yeah: need to ensure that any given directory-tree in `join-domain-formula/join-domain/elx` is essentially an exclusive-execution (i.e., if `centrify` is selected for execution, none of `openldap-clients`, `pbis`, `quest`, `sssd` or `winbind` is executed - unless specifically selecting a sub-module via "manual" run).

**Comment by lorengordon** [comment]
Sorry if I wasn't clear, but yes, they _are_ exclusive. The selecting pillar key can only be set to _one_ of the connectors. It is not going to try to run _all_ of them. All I am attempting to say is that the contract in the structure is that `<connector>/init.sls` actually joins the domain, where right now `openldap-clients/init.sls` does not.

**Comment by ferricoxide** [comment]
Ok. Just for clarification:

1. _You're_ saying, "given the standard pillar structure, this _won't_ get executed".
2. While _I'm_ saying "I'm only looking to make this _available_ for 'manual' execution - i.e., via someone specifically executing `salt-call --local ... join-domain.elx.openldap-clients` such that they can use the current contents as a work around for when the `adtool` utility is not usable.

Assuming the above, leaving this "as is" should be "ok". And that, if/when we get around to _fully_ realizing the `openldap-clients` functionality (and a given project actually needs to use it for its default `doman-join` functionality), would need to add the actual object-create and auth-setup logic calls to the `init.sls` (supplementing what's currently there) ...but for right now, what's there isn't going to pose a problem?

**Comment by lorengordon** [comment]
No. I'm saying that `openldap-clients/init.sls` _must_ implement the join. If in this PR the join is not being added, that the salt states must be moved to another sls file.

**Comment by ferricoxide** [comment]
Negative. At some point in time – when a full openldap-client configuration-state can be written – might make some tweaks _then_. But for now, this is where it needs to be.

**Pull request merged**
