### PR TITLE
Adds additonal required permissions for service account

### PR DESCRIPTION
**Pull request by eemperor**

### CODE REVIEW

**Comment by lorengordon** [comment]
Awesome, great find! For the appveyor failure, can fix that the same way we recently fixed it in ash-windows... https://github.com/plus3it/ash-windows-formula/pull/61/files

**Comment by eemperor** [comment]
Ah.  I just push an update to the urls but used `latest`.  I'll pin the version.

**Comment by lorengordon** [comment]
Oh that's nice, appveyor must have updated their default image. We *had* to add that key in ash-windows at the time, or the build failed because the old, deprecated image couldn't be found even though it was still the default.

**Review by lorengordon — APPROVED** [review]
:shipit:

**Pull request merged**
